const QUIZ_STATIC_DATA = {
    'it': [
        { domanda: "Qual è la formula chimica dell'acqua?", risposte: ["CO2", "H2O", "O2", "HO2"], corretta: 1 },
        { domanda: "A quale temperatura l'acqua raggiunge la sua massima densità?", risposte: ["0°C", "100°C", "4°C", "50°C"], corretta: 2 },
        { domanda: "Quale percentuale della superficie terrestre è coperta d'acqua?", risposte: ["50%", "71%", "90%", "30%"], corretta: 1 },
        { domanda: "Qual è l'unico elemento in natura presente in tre stati?", risposte: ["L'Acqua", "Il Carbonio", "Il Ferro", "L'Ossigeno"], corretta: 0 },
        { domanda: "Di tutta l'acqua sulla Terra, quanta è dolce e accessibile?", risposte: ["Circa il 20%", "Circa il 10%", "Meno dell'1%", "Circa il 50%"], corretta: 2 },
        { domanda: "Quanto del corpo umano adulto è composto d'acqua?", risposte: ["40%", "60%", "80%", "95%"], corretta: 1 },
        { domanda: "Qual è il pH dell'acqua pura a temperatura ambiente?", risposte: ["0", "7 (Neutro)", "14", "5"], corretta: 1 },
        { domanda: "Come si chiama il passaggio dallo stato liquido a quello gassoso?", risposte: ["Condensazione", "Sublimazione", "Evaporazione", "Fusione"], corretta: 2 },
        { domanda: "In quale stato l'acqua occupa più volume a parità di massa?", risposte: ["Liquido", "Solido (Ghiaccio)", "Gassoso", "Non cambia"], corretta: 1 },
        { domanda: "A che temperatura bolle l'acqua pura al livello del mare?", risposte: ["90°C", "100°C", "120°C", "80°C"], corretta: 1 },
        { domanda: "Qual è il legame chimico che unisce gli atomi di idrogeno e ossigeno nell'acqua?", risposte: ["Legame ionico", "Legame covalente", "Legame metallico", "Legame a idrogeno"], corretta: 1 },
        { domanda: "L'acqua è definita un solvente...", risposte: ["Universale", "Debole", "Inutile", "Solido"], corretta: 0 },
        { domanda: "Come si chiama la tensione sulla superficie dell'acqua?", risposte: ["Tensione superficiale", "Pressione idrica", "Forza d'urto", "Attrito"], corretta: 0 },
        { domanda: "Quale di questi organi umani contiene la più alta percentuale d'acqua?", risposte: ["Ossa", "Denti", "Cervello", "Unghie"], corretta: 2 },
        { domanda: "L'acqua del mare gela a una temperatura...", risposte: ["Più alta di 0°C", "Uguale a 0°C", "Più bassa di 0°C (circa -2°C)", "Non gela mai"], corretta: 2 },
        { domanda: "Quale processo rimuove il sale dall'acqua di mare?", risposte: ["Dissalazione", "Salinizzazione", "Elettrolisi", "Filtraggio a carbone"], corretta: 0 },
        { domanda: "Quanta acqua dovrebbe bere mediamente un adulto al giorno?", risposte: ["Mezzo litro", "Circa 2 litri", "10 litri", "Solo quando ha sete"], corretta: 1 },
        { domanda: "Cosa misura la 'durezza' dell'acqua?", risposte: ["La velocità", "Il calcare (Sali di calcio e magnesio)", "Il peso", "La trasparenza"], corretta: 1 },
        { domanda: "Il ghiaccio galleggia perché...", risposte: ["È più pesante", "È meno denso dell'acqua liquida", "È pieno d'aria", "Per magia"], corretta: 1 },
        { domanda: "Quale di queste sostanze non si scioglie in acqua?", risposte: ["Zucchero", "Sale", "Olio", "Sapone"], corretta: 2 },
        { domanda: "Quale antico acquedotto romano dissetava Napoli e la flotta imperiale di Miseno?", risposte: ["Acquedotto Carolino", "Acquedotto del Serino", "Acquedotto Vergine", "Acquedotto Traiano"], corretta: 1 },
        { domanda: "Come si chiamava l'acquedotto greco-romano che passava sotto il centro antico?", risposte: ["Acqua della Bolla", "Acqua del Vesuvio", "Acqua Cumana", "Acqua Sannitica"], corretta: 0 },
        { domanda: "Quale fiume sotterraneo e leggendario bagnava l'antica Neapolis?", risposte: ["Il Volturno", "Il Sebeto", "Il Sarno", "Il Clanio"], corretta: 1 },
        { domanda: "Chi era il 'Pozzaro' nella Napoli antica?", risposte: ["Il venditore di pozioni", "Il manutentore degli acquedotti e dei pozzi", "Il becchino", "Il pescatore"], corretta: 1 },
        { domanda: "Perché i Pozzari divennero famosi nel folklore napoletano?", risposte: ["Erano ricchi", "Scoprirono tesori", "Si credeva fossero il 'Munaciello'", "Inventarono la pizza"], corretta: 2 },
        { domanda: "Quale viceré spagnolo nel 1600 fece costruire un nuovo acquedotto?", risposte: ["Pedro de Toledo", "Conte di Lemos", "Cesare Carmignano", "Carlo di Borbone"], corretta: 2 },
        { domanda: "Dove si raccoglievano le acque piovane nei palazzi storici napoletani?", risposte: ["Nelle cisterne di tufo sotto i cortili", "Sui tetti a terrazza", "Nelle fontane", "Nelle cantine"], corretta: 0 },
        { domanda: "Quale grande serbatoio fu costruito scavando nel tufo di Capodimonte?", risposte: ["Serbatoio dello Scudillo", "Serbatoio di Posillipo", "Piscina Mirabilis", "Catacombe"], corretta: 0 },
        { domanda: "Secondo la mitologia, quale creatura diede origine a Napoli?", risposte: ["La Sirena Partenope", "La Ninfa Calipso", "La Dea Venere", "Il Mostro Scilla"], corretta: 0 },
        { domanda: "Dove si trovava la famosa 'Acqua Suffregna' tanto amata dai napoletani?", risposte: ["A Posillipo", "Al Chiatamone (Santa Lucia)", "Ai Quartieri Spagnoli", "Al Vomero"], corretta: 1 },
        { domanda: "Come veniva venduta l'Acqua Suffregna ai napoletani?", risposte: ["In bottiglie di vetro", "Nelle 'mummare' di creta", "In secchi di legno", "In fiaschi di paglia"], corretta: 1 },
        { domanda: "L'Acquedotto del Serino porta a Napoli acque provenienti da quale provincia?", risposte: ["Avellino (Monti Terminio)", "Salerno", "Benevento", "Caserta"], corretta: 0 },
        { domanda: "A Napoli esiste una via chiamata 'Cupa dell'Acqua'. Cos'è una 'Cupa'?", risposte: ["Una fontana", "Una strada incassata tra alte pareti di tufo", "Un secchio", "Una grotta"], corretta: 1 },
        { domanda: "Cos'era il 'Carro dell'Acqua' che un tempo girava per Napoli?", risposte: ["Un carro di Carnevale", "Il carretto dei venditori di acqua fresca", "Un carro dei pompieri", "Un pulitore stradale"], corretta: 1 },
        { domanda: "Nei periodi di siccità, chi aveva le chiavi delle cisterne sotterranee?", risposte: ["Il Re", "I 'Fontanieri' e i 'Pozzari'", "I sacerdoti", "Nessuno"], corretta: 1 },
        { domanda: "A chi è affidata oggi la tutela dell'acqua potabile di Napoli?", risposte: ["Al Sindaco", "All'Azienda ABC (Acqua Bene Comune)", "Alla Regione", "A un'azienda privata"], corretta: 1 },
        { domanda: "Quale architetto progettò il maestoso Acquedotto Carolino?", risposte: ["Domenico Fontana", "Cosimo Fanzago", "Luigi Vanvitelli", "Ferdinando Fuga"], corretta: 2 },
        { domanda: "A chi fu commissionato l'Acquedotto Carolino?", risposte: ["Ai Savoia", "Ai Borbone (Carlo di Borbone)", "Agli Angioini", "Agli Aragonesi"], corretta: 1 },
        { domanda: "Cos'è la 'Cisterna del Vico del Gargiulo'?", risposte: ["Un locale", "Una delle più grandi caverne/cisterne dell'Acquedotto della Bolla", "Una pentola", "Una piazza"], corretta: 1 },
        { domanda: "Come si chiamava il magistrato romano che amministrava gli acquedotti?", risposte: ["Curator Aquarum", "Centurione", "Gladiatore", "Prefetto"], corretta: 0 },
        { domanda: "Quanti litri d'acqua servono mediamente per produrre un singolo paio di jeans?", risposte: ["100 litri", "500 litri", "3.800 litri", "10.000 litri"], corretta: 2 },
        { domanda: "Quanto tempo impiega una bottiglietta di plastica per degradarsi in mare?", risposte: ["1 anno", "10 anni", "Fino a 450 anni", "Non si degrada mai"], corretta: 2 },
        { domanda: "Quanta acqua serve per produrre un solo chilogrammo di carne di manzo?", risposte: ["1.000 litri", "5.000 litri", "Oltre 15.000 litri", "100 litri"], corretta: 2 },
        { domanda: "Cosa sono le 'microplastiche' spesso citate nei problemi ambientali?", risposte: ["Piccoli pesci", "Frammenti di plastica inferiori a 5 mm", "Batteri dell'acqua", "Sali minerali"], corretta: 1 },
        { domanda: "Cosa risparmi utilizzando i beverini pubblici mappati in questa app?", risposte: ["Denaro e bottiglie di plastica monouso", "Elettricità", "Gas metano", "Solo tempo"], corretta: 0 },
        { domanda: "Quale settore umano consuma la maggior quantità di acqua dolce al mondo?", risposte: ["Uso domestico", "Industria", "Agricoltura e irrigazione", "Produzione di energia"], corretta: 2 },
        { domanda: "L'acqua erogata dai beverini pubblici di Napoli (ABC) è...", risposte: ["Non potabile", "Potabile, controllata e di ottima qualità", "Da bollire prima dell'uso", "Solo per uso tecnico"], corretta: 1 },
        { domanda: "Cos'è l'impronta idrica (Water Footprint)?", risposte: ["Il segno dei piedi bagnati", "Il volume totale di acqua dolce usata per produrre beni", "Il livello delle maree", "La profondità dei pozzi"], corretta: 1 },
        { domanda: "Quanta acqua si spreca lasciando il rubinetto aperto mentre ci si lava i denti?", risposte: ["Mezzo litro", "Circa 5-10 litri al minuto", "Nulla se il getto è piccolo", "100 litri"], corretta: 1 },
        { domanda: "Quanti litri d'acqua servono per produrre una singola tazza di caffè (dalla pianta alla tazzina)?", risposte: ["1 litro", "10 litri", "Circa 140 litri", "500 litri"], corretta: 2 },
        { domanda: "Cos'è il fenomeno dell'eutrofizzazione delle acque?", risposte: ["La pulizia dei fondali", "Eccesso di nutrienti che causa proliferazione di alghe", "Il congelamento dei laghi", "L'evaporazione"], corretta: 1 },
        { domanda: "Quale capo d'abbigliamento richiede circa 2.500 litri d'acqua per essere prodotto?", risposte: ["Una maglietta di cotone", "Un paio di calzini", "Un cappello", "Una sciarpa di lana"], corretta: 0 },
        { domanda: "Cosa si intende in ecologia per 'Acque Grigie'?", risposte: ["Acqua piovana sporca", "Acque reflue di lavandini e docce riutilizzabili", "Acqua del mare in tempesta", "Liquami fognari"], corretta: 1 },
        { domanda: "Quale tecnica di irrigazione agricola è la più efficiente per risparmiare acqua?", risposte: ["Irrigazione a pioggia", "Allagamento", "Irrigazione a goccia", "Uso di idranti"], corretta: 2 },
        { domanda: "Quanta acqua spreca un rubinetto che perde una goccia al secondo in un anno?", risposte: ["10 litri", "100 litri", "Oltre 3.000 litri", "Un milione di litri"], corretta: 2 },
        { domanda: "Quale obiettivo dell'Agenda 2030 ONU è dedicato all'acqua pulita?", risposte: ["Obiettivo 1", "Obiettivo 6", "Obiettivo 10", "Obiettivo 12"], corretta: 1 },
        { domanda: "Perché l'acqua del rubinetto è più ecologica di quella in bottiglia?", risposte: ["Costa meno", "Non richiede plastica e trasporti inquinanti", "Ha un sapore migliore", "Arriva più velocemente"], corretta: 1 },
        { domanda: "Quanta acqua occorre per produrre e sbiancare un singolo foglio di carta A4?", risposte: ["Un cucchiaio", "Circa 10 litri", "Un secchio", "Nulla"], corretta: 1 },
        { domanda: "In quale data si celebra la Giornata Mondiale dell'Acqua (World Water Day)?", risposte: ["1 Gennaio", "22 Marzo", "15 Agosto", "25 Dicembre"], corretta: 1 },
        { domanda: "Cosa succede alle cellule umane se beviamo acqua di mare per dissetarci?", risposte: ["Si idratano meglio", "Si disidratano per espellere il sale in eccesso", "Diventano blu", "Nulla"], corretta: 1 },
        { domanda: "Qual è il fiume più lungo del mondo?", risposte: ["Rio delle Amazzoni", "Nilo", "Mississippi", "Yangtze"], corretta: 1 },
        { domanda: "In quale corpo idrico la concentrazione di sale è così alta da far galleggiare le persone?", risposte: ["Mar Rosso", "Mar Morto", "Oceano Indiano", "Lago di Garda"], corretta: 1 },
        { domanda: "Qual è la cascata più alta del mondo?", risposte: ["Niagara", "Cascate Vittoria", "Salto Angel", "Iguazù"], corretta: 2 },
        { domanda: "Dove si trova la maggior parte dell'acqua dolce della Terra?", risposte: ["Nei fiumi", "Nei laghi", "Nelle nuvole", "Nei ghiacciai e calotte polari"], corretta: 3 },
        { domanda: "Quale oceano copre quasi il 30% della superficie terrestre?", risposte: ["Atlantico", "Indiano", "Pacifico", "Artico"], corretta: 2 },
        { domanda: "Quale lago è il più profondo della Terra?", risposte: ["Lago Superiore", "Lago Vittoria", "Lago Baikal", "Lago di Como"], corretta: 2 },
        { domanda: "Cos'è un 'fiordo'?", risposte: ["Una foresta", "Un'insenatura costiera scavata da un ghiacciaio", "Un'isola vulcanica", "Una cascata"], corretta: 1 },
        { domanda: "Quale pianeta è chiamato 'Pianeta Blu'?", risposte: ["Marte", "Terra", "Giove", "Venere"], corretta: 1 },
        { domanda: "Di cosa sono fatte prevalentemente le nuvole?", risposte: ["Gas", "Goccioline d'acqua o cristalli di ghiaccio", "Fumo", "Aria calda"], corretta: 1 },
        { domanda: "Come si chiama la paura irrazionale dell'acqua?", risposte: ["Aracnofobia", "Idrofobia o Acquafobia", "Claustrofobia", "Acrofobia"], corretta: 1 },
        { domanda: "Quale animale marino è composto per il 95% di acqua?", risposte: ["Delfino", "Balena", "Squalo", "Medusa"], corretta: 3 },
        { domanda: "Qual è il fiume più lungo d'Italia?", risposte: ["Tevere", "Arno", "Po", "Adige"], corretta: 2 },
        { domanda: "Come si chiama il ciclo continuo dell'acqua sulla Terra?", risposte: ["Ciclo Termico", "Ciclo Idrologico", "Ciclo di Krebs", "Riciclo"], corretta: 1 },
        { domanda: "Quale forza permette agli insetti di camminare sull'acqua?", risposte: ["Gravità", "Tensione superficiale", "Magnetismo", "Vento"], corretta: 1 },
        { domanda: "Quanti fiocchi di neve esattamente identici esistono in natura?", risposte: ["Miliardi", "Nessuno (sono unici)", "Solo due", "Cento"], corretta: 1 },
        { domanda: "Cos'è la desalinizzazione?", risposte: ["Aggiungere sale", "Togliere il sale dall'acqua marina", "Inquinare", "Bollire"], corretta: 1 },
        { domanda: "Quale dio greco/romano regna sui mari col tridente?", risposte: ["Giove", "Marte", "Nettuno", "Vulcano"], corretta: 2 },
        { domanda: "Quanti giorni può sopravvivere un uomo senza bere?", risposte: ["10 giorni", "3-5 giorni", "1 mese", "1 giorno"], corretta: 1 },
        { domanda: "Quale celebre fiaba parla di una creatura marina che vuole vivere sulla terra?", risposte: ["Cenerentola", "La Sirenetta", "Biancaneve", "Pollicino"], corretta: 1 },
        { domanda: "Cosa misura un pluviometro?", risposte: ["Profondità", "Umidità", "Quantità di pioggia", "Vento"], corretta: 2 },
        { domanda: "Quale quartiere di Napoli era famoso per le sue acque termali già in epoca romana?", risposte: ["Agnano", "Vomero", "Chiaia", "Sanità"], corretta: 0 },
        { domanda: "Come venivano chiamati i venditori ambulanti di acqua che giravano per i vicoli?", risposte: ["Acquaioli", "Pozzari", "Luciani", "Marenari"], corretta: 0 },
        { domanda: "Quale di queste fontane napoletane raffigura una sirena?", risposte: ["Fontana del Carciofo", "Fontana di Spinacorona", "Fontana del Formiello", "Fontana del Nettuno"], corretta: 1 },
        { domanda: "Cosa si intende per 'mummara' nel gergo tradizionale napoletano?", risposte: ["Una statua", "Un'anfora di creta per l'acqua", "Un tipo di pesce", "Una barca"], corretta: 1 },
        { domanda: "In quale piazza si trova la maestosa Fontana del Nettuno oggi?", risposte: ["Piazza Dante", "Piazza Municipio", "Piazza Bovio", "Piazza del Plebiscito"], corretta: 1 },
        { domanda: "Quale fontana è situata vicino al Castel dell'Ovo?", risposte: ["Fontana del Gigante", "Fontana del Sebeto", "Fontana del Carciofo", "Fontana della Sirena"], corretta: 0 },
        { domanda: "L'Acquedotto della Bolla portava l'acqua prelevandola da quale zona?", risposte: ["Campi Flegrei", "Piana di Volla", "Vesuvio", "Penisola Sorrentina"], corretta: 1 },
        { domanda: "Quale di queste fontane è famosa per i suoi 'giochi d'acqua' alla Mostra d'Oltremare?", risposte: ["Fontana dell'Esedra", "Fontana del Nettuno", "Fontana del Gigante", "Fontana della Tazza"], corretta: 0 },
        { domanda: "Il mito del 'Munaciello' è legato ai manutentori di quale infrastruttura?", risposte: ["Mura della città", "Acquedotti e cisterne", "Porto di Napoli", "Palazzi reali"], corretta: 1 },
        { domanda: "Quale re ordinò la costruzione della Fontana di Monteoliveto?", risposte: ["Carlo II di Spagna", "Ferdinando I", "Gioacchino Murat", "Vittorio Emanuele"], corretta: 0 },
        { domanda: "Cosa si intende per 'acqua pesante'?", risposte: ["Acqua con molto calcare", "Acqua contenente deuterio", "Acqua delle profondità marine", "Acqua ghiacciata"], corretta: 1 },
        { domanda: "Quale di queste lune di Giove nasconde un immenso oceano sotto il ghiaccio?", risposte: ["Io", "Ganimede", "Europa", "Callisto"], corretta: 2 },
        { domanda: "Come si chiama il processo naturale di filtraggio dell'acqua nel suolo?", risposte: ["Percolazione", "Evaporazione", "Erosione", "Sedimentazione"], corretta: 0 },
        { domanda: "Qual è il principale gas serra che viene influenzato dal ciclo dell'acqua?", risposte: ["Metano", "Anidride Carbonica", "Vapore acqueo", "Ozono"], corretta: 2 },
        { domanda: "In media, quanta acqua dolce mondiale è contenuta nel Lago Baikal?", risposte: ["Circa il 5%", "Circa il 20%", "Circa il 50%", "Meno dell'1%"], corretta: 1 },
        { domanda: "Cos'è la 'capillarità' dell'acqua?", risposte: ["La capacità di sciogliere il sale", "La capacità di risalire in tubi stretti contro la gravità", "La velocità di congelamento", "La trasparenza"], corretta: 1 },
        { domanda: "Qual è la salinità media degli oceani?", risposte: ["15 grammi per litro", "35 grammi per litro", "55 grammi per litro", "100 grammi per litro"], corretta: 1 },
        { domanda: "Chi scoprì che l'acqua è composta da Idrogeno e Ossigeno?", risposte: ["Galileo Galilei", "Henry Cavendish e Antoine Lavoisier", "Isaac Newton", "Charles Darwin"], corretta: 1 },
        { domanda: "Quale di queste piante è nota per purificare l'acqua assorbendo metalli pesanti?", risposte: ["Il Cactus", "Il Giacinto d'acqua", "La Rosa", "Il Pino"], corretta: 1 },
        { domanda: "Come si chiama l'acqua che si trova tra le fessure delle rocce nel sottosuolo?", risposte: ["Acqua fossile", "Falda acquifera", "Acqua meteorica", "Acqua di scolo"], corretta: 1 },
        { domanda: "Qual è il fiume più profondo del mondo?", risposte: ["Rio delle Amazzoni", "Fiume Congo", "Nilo", "Gange"], corretta: 1 },
        { domanda: "Quale paese possiede il maggior numero di laghi al mondo?", risposte: ["Canada", "Russia", "Stati Uniti", "Brasile"], corretta: 0 },
        { domanda: "Come si chiama lo stretto che separa l'Europa dall'Africa?", risposte: ["Stretto di Bering", "Stretto di Gibilterra", "Stretto di Magellano", "Bosforo"], corretta: 1 },
        { domanda: "Qual è il mare più salato della Terra (escludendo i laghi)?", risposte: ["Mar Mediterraneo", "Mar Rosso", "Mar dei Caraibi", "Mar Nero"], corretta: 1 },
        { domanda: "Quale di queste città è famosa per i suoi canali e viene chiamata 'La Serenissima'?", risposte: ["Amsterdam", "Venezia", "Bruges", "Napoli"], corretta: 1 },
        { domanda: "Qual è la cascata più larga del mondo (per estensione del fronte)?", risposte: ["Cascate del Niagara", "Cascate Vittoria", "Cascate di Khone Phapheng", "Salto Angel"], corretta: 2 },
        { domanda: "In quale oceano si trova la Fossa delle Marianne, il punto più profondo della Terra?", risposte: ["Oceano Atlantico", "Oceano Indiano", "Oceano Pacifico", "Oceano Artico"], corretta: 2 },
        { domanda: "Quale grande fiume attraversa ben 10 nazioni europee?", risposte: ["Reno", "Danubio", "Senna", "Tevere"], corretta: 1 },
        { domanda: "Qual è il più grande mare chiuso (lago salato) del mondo?", risposte: ["Mar Morto", "Mar Caspio", "Lago d'Aral", "Lago Ciad"], corretta: 1 },
        { domanda: "Quale deserto è considerato il luogo più arido del pianeta?", risposte: ["Sahara", "Deserto di Atacama", "Gobi", "Deserto del Kalahari"], corretta: 1 },
        { domanda: "Quale materiale veniva estratto nel sottosuolo di Napoli, creando le cisterne per l'acqua?", risposte: ["Marmo", "Tufo giallo", "Granito", "Carbone"], corretta: 1 },
        { domanda: "Durante la Seconda Guerra Mondiale, a cosa servirono le antiche cisterne di Napoli?", risposte: ["Depositi di cibo", "Rifugi antiaerei per i cittadini", "Ospedali segreti", "Prigioni"], corretta: 1 },
        { domanda: "Cos'è il 'Cimitero delle Fontanelle' a Napoli?", risposte: ["Una fontana abbandonata", "Un antico ossario ricavato in una cava di tufo", "Un parco acquatico", "Un museo delle navi"], corretta: 1 },
        { domanda: "Quale storica via di Napoli è famosa per i suoi laboratori di presepi e le cisterne greche?", risposte: ["Via Toledo", "Via San Gregorio Armeno", "Spaccanapoli", "Corso Umberto"], corretta: 1 },
        { domanda: "A che profondità media si trova il percorso di Napoli Sotterranea?", risposte: ["10 metri", "Circa 40 metri", "100 metri", "2 metri"], corretta: 1 },
        { domanda: "Come veniva chiamata l'acqua che sgorgava spontaneamente dalle rocce a Napoli?", risposte: ["Acqua di sorgiva", "Acqua della Bolla", "Acqua minerale", "Acqua di pozzo"], corretta: 1 },
        { domanda: "Oltre ai Pozzari, chi altro conosceva i segreti dei passaggi sotterranei?", risposte: ["I lupi", "I ladri di professione", "I re spagnoli", "I pescatori"], corretta: 1 },
        { domanda: "Quale importante tunnel borbonico collegava il Palazzo Reale con la caserma?", risposte: ["Galleria Umberto", "Galleria Borbonica", "Tunnel della Vittoria", "Sottopasso"], corretta: 1 },
        { domanda: "Cosa si trova ancora oggi sul fondo di alcune cisterne abbandonate di Napoli?", risposte: ["Tesori dei pirati", "Rottami di auto e moto d'epoca (gettatati dopo la guerra)", "Statue romane d'oro", "Niente, sono vuote"], corretta: 1 },
        { domanda: "L'acqua del Serino arrivò a Napoli in epoca moderna nel...", risposte: ["1885", "1950", "1700", "1999"], corretta: 0 },
        { domanda: "Quale città italiana è famosa per le sue 'Nasone', tipiche fontanelle in ghisa?", risposte: ["Milano", "Roma", "Napoli", "Firenze"], corretta: 1 },
        { domanda: "Come si chiama l'imponente cascata artificiale creata dai Romani in Umbria?", risposte: ["Cascata delle Marmore", "Cascata del Toce", "Cascata del Liri", "Cascata di Tivoli"], corretta: 0 },
        { domanda: "Qual è il principale componente del ghiaccio secco?", risposte: ["Acqua congelata", "Anidride carbonica solida", "Azoto liquido", "Ossigeno"], corretta: 1 },
        { domanda: "In quale mare sfocia il fiume Po?", risposte: ["Mar Tirreno", "Mar Adriatico", "Mar Ionio", "Mar Ligure"], corretta: 1 },
        { domanda: "Quale di questi animali può percepire le vibrazioni dell'acqua a chilometri di distanza?", risposte: ["Elefante", "Balena", "Cane", "Aquila"], corretta: 1 },
        { domanda: "Come si chiama lo strumento che misura la profondità del mare tramite ultrasuoni?", risposte: ["Bussola", "Ecoscandaglio", "Tachimetro", "Barometro"], corretta: 1 },
        { domanda: "Quale di questi è un lago di origine vulcanica vicino Roma?", risposte: ["Lago di Garda", "Lago di Bracciano", "Lago Trasimeno", "Lago Maggiore"], corretta: 1 },
        { domanda: "In media, quanto tempo può resistere un cammello senza bere in inverno?", risposte: ["2 giorni", "Fino a 6-7 mesi", "1 anno", "2 settimane"], corretta: 1 },
        { domanda: "Qual è la più grande riserva di acqua dolce sulla Terra dopo i ghiacciai?", risposte: ["I fiumi", "Le acque sotterranee (falde)", "I laghi", "L'atmosfera"], corretta: 1 },
        { domanda: "Quale di queste fontane napoletane si trova vicino a una famosa accademia d'arte?", risposte: ["Fontana di Monteoliveto", "Fontana del Nettuno", "Fontana del Gigante", "Fontana del Carciofo"], corretta: 0 },
        { domanda: "Quale mostro mitologico, insieme a Scilla, creava pericolosi vortici nello Stretto di Messina?", risposte: ["Cariddi", "Medusa", "Idra", "Polifemo"], corretta: 0 },
        { domanda: "Nella mitologia greca, chi è il messaggero degli abissi, figlio di Poseidone, che usa una conchiglia come tromba?", risposte: ["Tritone", "Eolo", "Ermes", "Atlante"], corretta: 0 },
        { domanda: "Quale celebre pittore rinascimentale ha dipinto 'La Nascita di Venere' che sorge dalle acque?", risposte: ["Leonardo da Vinci", "Sandro Botticelli", "Raffaello", "Michelangelo"], corretta: 1 },
        { domanda: "Come si chiama la ninfa trasformata in fonte che viene celebrata a Siracusa?", risposte: ["Dafne", "Aretusa", "Eco", "Calipso"], corretta: 1 },
        { domanda: "Quale fiume infernale, secondo il mito, portava l'oblio a chi ne beveva le acque?", risposte: ["Stige", "Acheronte", "Lete", "Flegetonte"], corretta: 2 },
        { domanda: "Chi dipinse le famose 'Ninfee', catturando i riflessi dell'acqua nel suo giardino di Giverny?", risposte: ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dalì"], corretta: 0 },
        { domanda: "Quale leggendaria città sommersa fu descritta per la prima volta da Platone?", risposte: ["Eldorado", "Atlantide", "Avalon", "Agartha"], corretta: 1 },
        { domanda: "Nella tradizione napoletana, quale santo è invocato contro la siccità e per benedire le acque?", risposte: ["San Gennaro", "San Giovanni Battista", "San Pasquale", "Sant'Antonio"], corretta: 1 },
        { domanda: "Quale creatura mitologica ha il corpo di cavallo e la coda di pesce?", risposte: ["Centauro", "Ippocampo", "Grifone", "Chimera"], corretta: 1 },
        { domanda: "Cos'è un 'Ninfeo' nell'architettura classica?", risposte: ["Una prigione", "Un monumento dedicato alle ninfe, spesso con fontane", "Un tempio solare", "Un mercato"], corretta: 1 },
        { domanda: "Quale organo del corpo umano filtra circa 180 litri di sangue al giorno per produrre urina?", risposte: ["Cuore", "Polmoni", "Reni", "Fegato"], corretta: 2 },
        { domanda: "Qual è il termine scientifico per il 'nuoto' dei pesci che permette loro di estrarre ossigeno dall'acqua?", risposte: ["Ventilazione branchiale", "Respirazione cutanea", "Osmosi", "Foto-sintesi"], corretta: 0 },
        { domanda: "Come si chiama l'acqua che contiene un'alta concentrazione di anidride carbonica naturale?", risposte: ["Acqua distillata", "Acqua acidula o effervescente naturale", "Acqua salmastra", "Acqua pesante"], corretta: 1 },
        { domanda: "Quale di questi materiali è il miglior isolante termico per mantenere l'acqua fredda?", risposte: ["Metallo", "Vetro", "Sughero", "Plastica sottile"], corretta: 2 },
        { domanda: "Qual è la velocità approssimativa del suono nell'acqua rispetto all'aria?", risposte: ["Uguale", "Circa 4 volte più veloce", "Molto più lenta", "L'acqua non trasmette suoni"], corretta: 1 },
        { domanda: "Che cos'è un 'Atollo'?", risposte: ["Una montagna sottomarina", "Un'isola corallina a forma di anello con una laguna interna", "Un tipo di corrente", "Una grotta"], corretta: 1 },
        { domanda: "Come si chiama l'esplorazione dei fondali marini tramite onde sonore?", risposte: ["Sonar", "Radar", "Laser", "Telescopio"], corretta: 0 },
        { domanda: "Qual è la densità dell'acqua dolce?", risposte: ["10 kg/m³", "1000 kg/m³ (o 1 kg per litro)", "500 kg/m³", "1 kg per metro cubo"], corretta: 1 },
        { domanda: "In quale parte del mondo si trova la più grande barriera corallina?", risposte: ["Mar Mediterraneo", "Oceano Pacifico (Australia)", "Mar dei Caraibi", "Oceano Indiano"], corretta: 1 },
        { domanda: "Cos'è la 'rugiada'?", risposte: ["Pioggia leggera", "Vapore acqueo atmosferico condensato al suolo di notte", "Neve sciolta", "Acqua di falda"], corretta: 1 }
    ],
    'en': [
        { domanda: "What is the chemical formula of water?", risposte: ["CO2", "H2O", "O2", "HO2"], corretta: 1 },
        { domanda: "At what temperature does pure water reach its maximum density?", risposte: ["0°C", "100°C", "4°C", "50°C"], corretta: 2 },
        { domanda: "What percentage of the Earth's surface is covered by water?", risposte: ["50%", "71%", "90%", "30%"], corretta: 1 },
        { domanda: "What is the only element in nature present in three states?", risposte: ["Water", "Carbon", "Iron", "Oxygen"], corretta: 0 },
        { domanda: "Of all the water on Earth, how much is fresh and accessible?", risposte: ["About 20%", "About 10%", "Less than 1%", "About 50%"], corretta: 2 },
        { domanda: "How much of the adult human body is composed of water?", risposte: ["40%", "60%", "80%", "95%"], corretta: 1 },
        { domanda: "What is the pH of pure water at room temperature?", risposte: ["0", "7 (Neutral)", "14", "5"], corretta: 1 },
        { domanda: "What is the change from liquid to gas called?", risposte: ["Condensation", "Sublimation", "Evaporation", "Melting"], corretta: 2 },
        { domanda: "In which state does water occupy more volume?", risposte: ["Liquid", "Solid (Ice)", "Gaseous", "No change"], corretta: 1 },
        { domanda: "At what temperature does pure water boil at sea level?", risposte: ["90°C", "100°C", "120°C", "80°C"], corretta: 1 },
        { domanda: "What is the chemical bond between hydrogen and oxygen in water?", risposte: ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"], corretta: 1 },
        { domanda: "Water is defined as a...", risposte: ["Universal solvent", "Weak solvent", "Useless solvent", "Solid solvent"], corretta: 0 },
        { domanda: "What is the tension on the water surface called?", risposte: ["Surface tension", "Water pressure", "Impact force", "Friction"], corretta: 0 },
        { domanda: "Which of these human organs contains the highest percentage of water?", risposte: ["Bones", "Teeth", "Brain", "Nails"], corretta: 2 },
        { domanda: "Seawater freezes at a temperature...", risposte: ["Higher than 0°C", "At 0°C", "Lower than 0°C (approx. -2°C)", "Never freezes"], corretta: 2 },
        { domanda: "Which process removes salt from seawater?", risposte: ["Desalination", "Salinization", "Electrolysis", "Carbon filtering"], corretta: 0 },
        { domanda: "How much water should an average adult drink per day?", risposte: ["Half a liter", "About 2 liters", "10 liters", "Only when thirsty"], corretta: 1 },
        { domanda: "What does water 'hardness' measure?", risposte: ["Speed", "Limescale (Calcium and magnesium salts)", "Weight", "Transparency"], corretta: 1 },
        { domanda: "Ice floats because...", risposte: ["It's heavier", "It's less dense than liquid water", "It's full of air", "Magic"], corretta: 1 },
        { domanda: "Which of these substances does not dissolve in water?", risposte: ["Sugar", "Salt", "Oil", "Soap"], corretta: 2 },
        { domanda: "Which ancient Roman aqueduct supplied Naples and the imperial fleet at Misenum?", risposte: ["Carolino Aqueduct", "Serino Aqueduct", "Virgo Aqueduct", "Trajan Aqueduct"], corretta: 1 },
        { domanda: "What was the name of the Greco-Roman aqueduct that passed under the ancient center?", risposte: ["Acqua della Bolla", "Vesuvius Water", "Cumana Water", "Samnite Water"], corretta: 0 },
        { domanda: "Which legendary underground river flowed through ancient Neapolis?", risposte: ["Volturno", "Sebeto", "Sarno", "Clanio"], corretta: 1 },
        { domanda: "Who was the 'Pozzaro' in ancient Naples?", risposte: ["A potion seller", "Maintainer of aqueducts and wells", "A gravedigger", "A fisherman"], corretta: 1 },
        { domanda: "Why did the Pozzari become famous in Neapolitan folklore?", risposte: ["They were rich", "They found treasures", "They were thought to be the 'Munaciello'", "They invented pizza"], corretta: 2 },
        { domanda: "Which Spanish viceroy in 1600 built a new aqueduct for the city?", risposte: ["Pedro de Toledo", "Count of Lemos", "Cesare Carmignano", "Charles of Bourbon"], corretta: 2 },
        { domanda: "Where was rainwater collected in historic Neapolitan palaces?", risposte: ["In tuff cisterns under courtyards", "On terrace roofs", "In fountains", "In cellars"], corretta: 0 },
        { domanda: "Which large water reservoir was built by excavating the tuff of Capodimonte?", risposte: ["Scudillo reservoir", "Posillipo reservoir", "Piscina Mirabilis", "Catacombs"], corretta: 0 },
        { domanda: "According to mythology, which creature gave birth to Naples?", risposte: ["Siren Parthenope", "Nymph Calypso", "Goddess Venus", "Monster Scylla"], corretta: 0 },
        { domanda: "Where was the famous 'Acqua Suffregna' loved by Neapolitans located?", risposte: ["In Posillipo", "At Chiatamone (Santa Lucia)", "In Spanish Quarters", "In Vomero"], corretta: 1 },
        { domanda: "How was 'Acqua Suffregna' sold to Neapolitans?", risposte: ["In glass bottles", "In clay 'mummare' jars", "In wooden buckets", "In straw flasks"], corretta: 1 },
        { domanda: "The Serino Aqueduct brings water to Naples from which province?", risposte: ["Avellino (Terminio Mountains)", "Salerno", "Benevento", "Caserta"], corretta: 0 },
        { domanda: "In Naples there is a street called 'Cupa dell'Acqua'. What is a 'Cupa'?", risposte: ["A fountain", "A road embedded between high tuff walls", "A bucket", "A cave"], corretta: 1 },
        { domanda: "What was the 'Carro dell'Acqua' that once went around Naples?", risposte: ["A Carnival float", "The cart of fresh water sellers", "A fire truck", "A street cleaner"], corretta: 1 },
        { domanda: "In periods of drought, who held the keys to the underground cisterns?", risposte: ["The King", "The 'Fontanieri' and 'Pozzari'", "The priests", "Nobody"], corretta: 1 },
        { domanda: "Who is in charge of protecting Naples' drinking water today?", risposte: ["The Mayor", "The ABC Company (Acqua Bene Comune)", "The Region", "A private company"], corretta: 1 },
        { domanda: "Which architect designed the majestic Carolino Aqueduct?", risposte: ["Domenico Fontana", "Cosimo Fanzago", "Luigi Vanvitelli", "Ferdinando Fuga"], corretta: 2 },
        { domanda: "To whom was the Carolino Aqueduct commissioned?", risposte: ["The Savoy", "The Bourbons (Charles of Bourbon)", "The Angevins", "The Aragonese"], corretta: 1 },
        { domanda: "What is the 'Cisterna del Vico del Gargiulo'?", risposte: ["A club", "One of the largest cisterns of the Bolla Aqueduct", "A pot", "A square"], corretta: 1 },
        { domanda: "What was the name of the Roman magistrate in charge of aqueducts?", risposte: ["Curator Aquarum", "Centurion", "Gladiator", "Prefect"], corretta: 0 },
        { domanda: "Cosa raffigura la strana Fontana di Spinacorona?", risposte: ["Un drago che sputa fuoco", "Una sirena che spegne le fiamme del Vesuvio", "Un re a cavallo", "Un angelo con la spada"], corretta: 1 },
        { domanda: "Come è chiamata dai napoletani la Fontana di Spinacorona?", risposte: ["Fontana delle Zizze", "Fontana della Sirena", "Fontana del Latte", "Fontana del Fuoco"], corretta: 0 },
        { domanda: "Dove si trova la Fontana del Carciofo?", risposte: ["Piazza Dante", "Piazza Trieste e Trento", "Piazza Plebiscito", "Piazza Vittoria"], corretta: 1 },
        { domanda: "Cosa regge il Nettuno nell'omonima fontana di Piazza Municipio?", risposte: ["Un tridente", "Un pesce", "Una conchiglia", "Una spada"], corretta: 0 },
        { domanda: "Dove si trovava in origine la Fontana del Nettuno?", risposte: ["A Roma", "Presso l'Arsenale del Porto", "A Caserta", "A Capodimonte"], corretta: 1 },
        { domanda: "Quale fontana si trova oggi sul lungomare, vicino Castel dell'Ovo?", risposte: ["Fontana del Gigante", "Fontana del Sebeto", "Fontana di Monteoliveto", "Fontana del Formiello"], corretta: 0 },
        { domanda: "La Fontana del Gigante è conosciuta anche come...", risposte: ["Fontana dell'Immacolatella", "Fontana del Re", "Fontana dei Leoni", "Fontana del Sole"], corretta: 0 },
        { domanda: "Quale celebre architetto lavorò a molte fontane napoletane del '600?", risposte: ["Michelangelo", "Cosimo Fanzago", "Bernini", "Canova"], corretta: 1 },
        { domanda: "Quale fontana decora la piazza davanti alla chiesa di Sant'Anna dei Lombardi?", risposte: ["Fontana di Monteoliveto", "Fontana del Nettuno", "Fontana del Carciofo", "Fontana del Sebeto"], corretta: 0 },
        { domanda: "La fontana dell'Esedra, la più grande della città, dove si trova?", risposte: ["Mostra d'Oltremare", "Piazza Garibaldi", "Bosco di Capodimonte", "Lungomare Caracciolo"], corretta: 0 },
        { domanda: "Cosa riproduce la Fontana del Formiello dietro Castel Capuano?", risposte: ["Un tempio greco", "Un abbeveratoio monumentale", "Una barca a vela", "Un castello"], corretta: 1 },
        { domanda: "Quale fontana si trova al centro di Piazza Vittoria?", risposte: ["Fontana della Tazza di Pido", "Fontana del Ratto di Europa", "Nessuna, c'è una statua", "Fontana del Sebeto"], corretta: 0 },
        { domanda: "La maestosa Fontana del Sebeto si trova attualmente in...", risposte: ["Via Caracciolo", "Largo Sermoneta (Via Posillipo)", "Piazza Municipio", "Piazza del Carmine"], corretta: 1 },
        { domanda: "Cosa si usava per proteggere le fontane monumentali dai lavandai nel '700?", risposte: ["Guardie armate", "Imponenti cancellate di ferro", "Cani", "Acqua colorata"], corretta: 1 },
        { domanda: "Nella Fontana della Sirena a Mergellina, quali animali marini sorreggono la vasca?", risposte: ["Quattro delfini", "Quattro cavallucci marini", "Tre balene", "Quattro tartarughe"], corretta: 1 },
        { domanda: "In quale piazza fu spostata la Fontana del Nettuno nel 2015?", risposte: ["Piazza Dante", "Piazza Municipio", "Piazza Borsa", "Piazza Vittoria"], corretta: 1 },
        { domanda: "Quale fontana raffigura un Re bambino circondato da tre leoni?", risposte: ["Fontana del Carciofo", "Fontana di Monteoliveto", "Fontana del Nettuno", "Fontana della Sirena"], corretta: 1 },
        { domanda: "La Fontana degli Incanti si trova attualmente a...", risposte: ["Piazza San Luigi (Posillipo)", "Piazza dei Martiri", "Via Toledo", "Molo Beverello"], corretta: 0 },
        { domanda: "Da chi fu commissionata la Fontana del Formiello?", risposte: ["Don Pedro de Toledo", "Masaniello", "I monaci", "L'Imperatore Augusto"], corretta: 0 },
        { domanda: "Quale fontana è famosa per essere stata spostata almeno 7 volte?", risposte: ["Fontana del Nettuno", "Fontana del Carciofo", "Fontana del Sebeto", "Fontana del Gigante"], corretta: 0 }, 
        { domanda: "How many liters of water are needed on average to produce a single pair of jeans?", risposte: ["100 liters", "500 liters", "3,800 liters", "10,000 liters"], corretta: 2 },
        { domanda: "How long does a plastic bottle take to degrade in the sea?", risposte: ["1 year", "10 years", "Up to 450 years", "It never degrades"], corretta: 2 },
        { domanda: "How much water is needed to produce just one kilogram of beef?", risposte: ["1,000 liters", "5,000 liters", "Over 15,000 liters", "100 liters"], corretta: 2 },
        { domanda: "What are 'microplastics' often mentioned in environmental issues?", risposte: ["Small fish", "Plastic fragments smaller than 5 mm", "Water bacteria", "Mineral salts"], corretta: 1 },
        { domanda: "What do you save by using the public water dispensers mapped in this app?", risposte: ["Money and single-use plastic bottles", "Electricity", "Methane gas", "Only time"], corretta: 0 },
        { domanda: "Which human sector consumes the largest amount of freshwater in the world?", risposte: ["Domestic use", "Industry", "Agriculture and irrigation", "Energy production"], corretta: 2 },
        { domanda: "The water provided by Naples' public dispensers (ABC) is...", risposte: ["Not drinkable", "Drinkable, controlled and of excellent quality", "To be boiled before use", "Only for technical use"], corretta: 1 },
        { domanda: "What is the Water Footprint?", risposte: ["The mark of wet feet", "The total volume of freshwater used to produce goods", "Tide level", "Depth of wells"], corretta: 1 },
        { domanda: "How much water is wasted by leaving the tap running while brushing your teeth?", risposte: ["Half a liter", "About 5-10 liters per minute", "Nothing if the flow is small", "100 liters"], corretta: 1 },
        { domanda: "How many liters of water are needed to produce a single cup of coffee (from plant to cup)?", risposte: ["1 liter", "10 liters", "About 140 liters", "500 liters"], corretta: 2 },
        { domanda: "What is the phenomenon of water eutrophication?", risposte: ["Cleaning of the seabed", "Excess nutrients causing algae blooms", "Freezing of lakes", "Evaporation"], corretta: 1 },
        { domanda: "Which piece of clothing requires about 2,500 liters of water to be produced?", risposte: ["A cotton t-shirt", "A pair of socks", "A hat", "A wool scarf"], corretta: 0 },
        { domanda: "What is meant by 'Greywater' in ecology?", risposte: ["Dirty rainwater", "Reusable wastewater from sinks and showers", "Sea water in a storm", "Sewage"], corretta: 1 },
        { domanda: "Which agricultural irrigation technique is the most efficient for saving water?", risposte: ["Sprinkler irrigation", "Flooding", "Drip irrigation", "Use of hydrants"], corretta: 2 },
        { domanda: "How much water is wasted by a tap leaking one drop per second in a year?", risposte: ["10 liters", "100 liters", "Over 3,000 liters", "One million liters"], corretta: 2 },
        { domanda: "Which UN 2030 Agenda goal is dedicated to clean water?", risposte: ["Goal 1", "Goal 6", "Goal 10", "Goal 12"], corretta: 1 },
        { domanda: "Why is tap water more ecological than bottled water?", risposte: ["It costs less", "It doesn't require plastic and polluting transport", "It tastes better", "It arrives faster"], corretta: 1 },
        { domanda: "How much water is needed to produce and bleach a single A4 sheet of paper?", risposte: ["A tablespoon", "About 10 liters", "A bucket", "Nothing"], corretta: 1 },
        { domanda: "On what date is World Water Day celebrated?", risposte: ["January 1st", "March 22nd", "August 15th", "December 25th"], corretta: 1 },
        { domanda: "What happens to human cells if we drink seawater to quench our thirst?", risposte: ["They hydrate better", "They dehydrate to expel excess salt", "They turn blue", "Nothing"], corretta: 1 },
        { domanda: "What is the longest river in the world?", risposte: ["Amazon", "Nile", "Mississippi", "Yangtze"], corretta: 1 },
        { domanda: "In which body of water is the salt concentration so high that people float?", risposte: ["Red Sea", "Dead Sea", "Indian Ocean", "Lake Garda"], corretta: 1 },
        { domanda: "What is the highest waterfall in the world?", risposte: ["Niagara", "Victoria Falls", "Angel Falls", "Iguazu"], corretta: 2 },
        { domanda: "Where is most of the Earth's freshwater located?", risposte: ["Rivers", "Lakes", "Clouds", "Glaciers and polar ice caps"], corretta: 3 },
        { domanda: "Which ocean covers almost 30% of the Earth's surface?", risposte: ["Atlantic", "Indian", "Pacific", "Arctic"], corretta: 2 },
        { domanda: "Which lake is the deepest on Earth?", risposte: ["Lake Superior", "Lake Victoria", "Lake Baikal", "Lake Como"], corretta: 2 },
        { domanda: "What is a 'fjord'?", risposte: ["A forest", "A coastal inlet carved by a glacier", "A volcanic island", "A waterfall"], corretta: 1 },
        { domanda: "Which planet is called the 'Blue Planet'?", risposte: ["Mars", "Earth", "Jupiter", "Venus"], corretta: 1 },
        { domanda: "What are clouds predominantly made of?", risposte: ["Gas", "Water droplets or ice crystals", "Smoke", "Hot air"], corretta: 1 },
        { domanda: "What is the irrational fear of water called?", risposte: ["Arachnophobia", "Hydrophobia", "Claustrophobia", "Acrophobia"], corretta: 1 },
        { domanda: "Which sea animal is 95% water?", risposte: ["Dolphin", "Whale", "Shark", "Jellyfish"], corretta: 3 },
        { domanda: "What is the longest river in Italy?", risposte: ["Tiber", "Arno", "Po", "Adige"], corretta: 2 },
        { domanda: "What is the continuous water cycle on Earth called?", risposte: ["Thermal Cycle", "Hydrological Cycle", "Krebs Cycle", "Recycling"], corretta: 1 },
        { domanda: "What force allows insects to walk on water?", risposte: ["Gravity", "Surface tension", "Magnetism", "Wind"], corretta: 1 },
        { domanda: "How many exactly identical snowflakes exist in nature?", risposte: ["Billions", "None (they are unique)", "Only two", "One hundred"], corretta: 1 },
        { domanda: "What is desalination?", risposte: ["Adding salt", "Removing salt from seawater", "Polluting", "Boiling"], corretta: 1 },
        { domanda: "Which Greek/Roman god rules the seas with a trident?", risposte: ["Jupiter", "Mars", "Neptune", "Vulcan"], corretta: 2 },
        { domanda: "How many days can a human survive without drinking?", risposte: ["10 days", "3-5 days", "1 month", "1 day"], corretta: 1 },
        { domanda: "Which famous fairy tale is about a sea creature wanting to live on land?", risposte: ["Cinderella", "The Little Mermaid", "Snow White", "Tom Thumb"], corretta: 1 },
        { domanda: "What does a rain gauge measure?", risposte: ["Depth", "Humidity", "Amount of rain", "Wind"], corretta: 2 },
        { domanda: "Which district of Naples was famous for its thermal waters since Roman times?", risposte: ["Agnano", "Vomero", "Chiaia", "Sanità"], corretta: 0 },
        { domanda: "What were the street water sellers in the alleys called?", risposte: ["Acquaioli", "Pozzari", "Luciani", "Marenari"], corretta: 0 },
        { domanda: "Which of these Neapolitan fountains depicts a siren?", risposte: ["Artichoke Fountain", "Spinacorona Fountain", "Formiello Fountain", "Neptune Fountain"], corretta: 1 },
        { domanda: "What is a 'mummara' in traditional Neapolitan jargon?", risposte: ["A statue", "A clay water amphora", "A type of fish", "A boat"], corretta: 1 },
        { domanda: "In which square is the majestic Neptune Fountain located today?", risposte: ["Piazza Dante", "Piazza Municipio", "Piazza Bovio", "Piazza del Plebiscito"], corretta: 1 },
        { domanda: "Which fountain is located near Castel dell'Ovo?", risposte: ["Giant's Fountain", "Sebeto Fountain", "Artichoke Fountain", "Siren Fountain"], corretta: 0 },
        { domanda: "The Bolla Aqueduct brought water from which area?", risposte: ["Phlegraean Fields", "Plain of Volla", "Vesuvius", "Sorrento Peninsula"], corretta: 1 },
        { domanda: "Which of these fountains is famous for its water displays at Mostra d'Oltremare?", risposte: ["Esedra Fountain", "Neptune Fountain", "Giant's Fountain", "Tazza Fountain"], corretta: 0 },
        { domanda: "The myth of 'Munaciello' is linked to the maintainers of which infrastructure?", risposte: ["City walls", "Aqueducts and cisterns", "Port of Naples", "Royal palaces"], corretta: 1 },
        { domanda: "Which king ordered the construction of the Monteoliveto Fountain?", risposte: ["Charles II of Spain", "Ferdinand I", "Joachim Murat", "Victor Emmanuel"], corretta: 0 },
        { domanda: "What is meant by 'heavy water'?", risposte: ["Water with high limescale", "Water containing deuterium", "Deep sea water", "Frozen water"], corretta: 1 },
        { domanda: "Which of Jupiter's moons hides a vast ocean beneath its ice?", risposte: ["Io", "Ganymede", "Europa", "Callisto"], corretta: 2 },
        { domanda: "What is the natural process of water filtering through the soil called?", risposte: ["Percolation", "Evaporation", "Erosion", "Sedimentation"], corretta: 0 },
        { domanda: "What is the main greenhouse gas influenced by the water cycle?", risposte: ["Methane", "Carbon Dioxide", "Water Vapor", "Ozone"], corretta: 2 },
        { domanda: "On average, how much of the world's freshwater is in Lake Baikal?", risposte: ["About 5%", "About 20%", "About 50%", "Less than 1%"], corretta: 1 },
        { domanda: "What is water 'capillarity'?", risposte: ["Ability to dissolve salt", "Ability to rise in narrow tubes against gravity", "Freezing speed", "Transparency"], corretta: 1 },
        { domanda: "What is the average salinity of the oceans?", risposte: ["15 grams per liter", "35 grams per liter", "55 grams per liter", "100 grams per liter"], corretta: 1 },
        { domanda: "Who discovered that water is composed of Hydrogen and Oxygen?", risposte: ["Galileo Galilei", "Henry Cavendish & Antoine Lavoisier", "Isaac Newton", "Charles Darwin"], corretta: 1 },
        { domanda: "Which of these plants is known to purify water by absorbing heavy metals?", risposte: ["Cactus", "Water Hyacinth", "Rose", "Pine"], corretta: 1 },
        { domanda: "What is the water found in underground rock crevices called?", risposte: ["Fossil water", "Aquifer", "Meteoric water", "Runoff water"], corretta: 1 },
        { domanda: "What is the deepest river in the world?", risposte: ["Amazon River", "Congo River", "Nile", "Ganges"], corretta: 1 },
        { domanda: "Which country has the most lakes in the world?", risposte: ["Canada", "Russia", "United States", "Brazil"], corretta: 0 },
        { domanda: "What is the name of the strait that separates Europe from Africa?", risposte: ["Bering Strait", "Strait of Gibraltar", "Strait of Magellan", "Bosphorus"], corretta: 1 },
        { domanda: "What is the saltiest sea on Earth (excluding lakes)?", risposte: ["Mediterranean Sea", "Red Sea", "Caribbean Sea", "Black Sea"], corretta: 1 },
        { domanda: "Which of these cities is famous for its canals and is called 'La Serenissima'?", risposte: ["Amsterdam", "Venice", "Bruges", "Naples"], corretta: 1 },
        { domanda: "What is the widest waterfall in the world (by front width)?", risposte: ["Niagara Falls", "Victoria Falls", "Khone Phapheng Falls", "Angel Falls"], corretta: 2 },
        { domanda: "In which ocean is the Mariana Trench, the deepest point on Earth, located?", risposte: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"], corretta: 2 },
        { domanda: "Which large river flows through 10 European nations?", risposte: ["Rhine", "Danube", "Seine", "Tiber"], corretta: 1 },
        { domanda: "What is the largest enclosed sea (salt lake) in the world?", risposte: ["Dead Sea", "Caspian Sea", "Aral Sea", "Lake Chad"], corretta: 1 },
        { domanda: "Which desert is considered the driest place on the planet?", risposte: ["Sahara", "Atacama Desert", "Gobi", "Kalahari Desert"], corretta: 1 },
        { domanda: "What material was extracted from Naples' subsoil, creating the water cisterns?", risposte: ["Marble", "Yellow tuff", "Granite", "Coal"], corretta: 1 },
        { domanda: "During World War II, what were the ancient cisterns of Naples used for?", risposte: ["Food storage", "Air-raid shelters for citizens", "Secret hospitals", "Prisons"], corretta: 1 },
        { domanda: "What is the 'Cimitero delle Fontanelle' in Naples?", risposte: ["An abandoned fountain", "An ancient ossuary in a tuff quarry", "A water park", "A ship museum"], corretta: 1 },
        { domanda: "Which historic street in Naples is famous for nativity workshops and Greek cisterns?", risposte: ["Via Toledo", "Via San Gregorio Armeno", "Spaccanapoli", "Corso Umberto"], corretta: 1 },
        { domanda: "What is the average depth of the 'Naples Underground' tour?", risposte: ["10 meters", "About 40 meters", "100 meters", "2 meters"], corretta: 1 },
        { domanda: "What was the water that naturally gushed from the rocks in Naples called?", risposte: ["Spring water", "Acqua della Bolla", "Mineral water", "Well water"], corretta: 1 },
        { domanda: "Besides the Pozzari, who else knew the secrets of the underground passages?", risposte: ["Wolves", "Professional thieves", "Spanish kings", "Fishermen"], corretta: 1 },
        { domanda: "Which important Bourbon tunnel connected the Royal Palace to the barracks?", risposte: ["Galleria Umberto", "Bourbon Tunnel", "Victory Tunnel", "Underpass"], corretta: 1 },
        { domanda: "What can still be found today at the bottom of some abandoned cisterns in Naples?", risposte: ["Pirate treasures", "Vintage car and bike wreckage (thrown after the war)", "Golden Roman statues", "Nothing, they are empty"], corretta: 1 },
        { domanda: "The Serino water arrived in modern Naples in...", risposte: ["1885", "1950", "1700", "1999"], corretta: 0 },
        { domanda: "Which Italian city is famous for its 'Nasone', typical cast-iron fountains?", risposte: ["Milan", "Rome", "Naples", "Florence"], corretta: 1 },
        { domanda: "What is the name of the imposing artificial waterfall created by the Romans in Umbria?", risposte: ["Marmore Falls", "Toce Falls", "Liri Falls", "Tivoli Falls"], corretta: 0 },
        { domanda: "What is the main component of dry ice?", risposte: ["Frozen water", "Solid carbon dioxide", "Liquid nitrogen", "Oxygen"], corretta: 1 },
        { domanda: "Into which sea does the Po River flow?", risposte: ["Tyrrhenian Sea", "Adriatic Sea", "Ionian Sea", "Ligurian Sea"], corretta: 1 },
        { domanda: "Which of these animals can sense water vibrations from miles away?", risposte: ["Elephant", "Whale", "Dog", "Eagle"], corretta: 1 },
        { domanda: "What is the instrument that measures sea depth using ultrasound called?", risposte: ["Compass", "Echo sounder", "Speedometer", "Barometer"], corretta: 1 },
        { domanda: "Which of these is a lake of volcanic origin near Rome?", risposte: ["Lake Garda", "Lake Bracciano", "Lake Trasimeno", "Lake Maggiore"], corretta: 1 },
        { domanda: "On average, how long can a camel survive without drinking in winter?", risposte: ["2 days", "Up to 6-7 months", "1 year", "2 weeks"], corretta: 1 },
        { domanda: "What is the largest freshwater reserve on Earth after glaciers?", risposte: ["Rivers", "Groundwater (aquifers)", "Lakes", "Atmosphere"], corretta: 1 },
        { domanda: "Which of these Neapolitan fountains is located near a famous art academy?", risposte: ["Monteoliveto Fountain", "Neptune Fountain", "Giant's Fountain", "Artichoke Fountain"], corretta: 0 },
        { domanda: "Which mythological monster, along with Scylla, created dangerous whirlpools in the Strait of Messina?", risposte: ["Charybdis", "Medusa", "Hydra", "Polyphemus"], corretta: 0 },
        { domanda: "In Greek mythology, who is the messenger of the deep, son of Poseidon, who uses a conch shell as a trumpet?", risposte: ["Triton", "Aeolus", "Hermes", "Atlas"], corretta: 0 },
        { domanda: "Which famous Renaissance painter painted 'The Birth of Venus' rising from the waters?", risposte: ["Leonardo da Vinci", "Sandro Botticelli", "Raphael", "Michelangelo"], corretta: 1 },
        { domanda: "What is the name of the nymph transformed into a spring celebrated in Syracuse?", risposte: ["Daphne", "Arethusa", "Echo", "Calypso"], corretta: 1 },
        { domanda: "Which infernal river, according to myth, brought oblivion to those who drank its waters?", risposte: ["Styx", "Acheron", "Lethe", "Phlegethon"], corretta: 2 },
        { domanda: "Who painted the famous 'Water Lilies', capturing the reflections of water in his garden at Giverny?", risposte: ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dalì"], corretta: 0 },
        { domanda: "Which legendary sunken city was first described by Plato?", risposte: ["Eldorado", "Atlantis", "Avalon", "Agartha"], corretta: 1 },
        { domanda: "In Neapolitan tradition, which saint is invoked against drought and to bless the waters?", risposte: ["San Gennaro", "Saint John the Baptist", "San Pasquale", "Saint Anthony"], corretta: 1 },
        { domanda: "Which mythological creature has the body of a horse and the tail of a fish?", risposte: ["Centaur", "Hippocampus", "Griffin", "Chimera"], corretta: 1 },
        { domanda: "What is a 'Nymphaeum' in classical architecture?", risposte: ["A prison", "A monument dedicated to nymphs, often with fountains", "A solar temple", "A market"], corretta: 1 },
        { domanda: "Which organ in the human body filters about 180 liters of blood per day to produce urine?", risposte: ["Heart", "Lungs", "Kidneys", "Liver"], corretta: 2 },
        { domanda: "What is the scientific term for the way fish extract oxygen from water?", risposte: ["Branchial ventilation", "Cutaneous respiration", "Osmosis", "Photosynthesis"], corretta: 0 },
        { domanda: "What is water that contains a high concentration of natural carbon dioxide called?", risposte: ["Distilled water", "Acidulous or naturally sparkling water", "Brackish water", "Heavy water"], corretta: 1 },
        { domanda: "Which of these materials is the best thermal insulator to keep water cold?", risposte: ["Metal", "Glass", "Cork", "Thin plastic"], corretta: 2 },
        { domanda: "What is the approximate speed of sound in water compared to air?", risposte: ["The same", "About 4 times faster", "Much slower", "Water doesn't transmit sound"], corretta: 1 },
        { domanda: "What is an 'Atoll'?", risposte: ["An undersea mountain", "A ring-shaped coral island with a lagoon", "A type of current", "A cave"], corretta: 1 },
        { domanda: "What is the exploration of the seabed using sound waves called?", risposte: ["Sonar", "Radar", "Laser", "Telescope"], corretta: 0 },
        { domanda: "What is the density of freshwater?", risposte: ["10 kg/m³", "1000 kg/m³ (or 1 kg per liter)", "500 kg/m³", "1 kg per cubic meter"], corretta: 1 },
        { domanda: "In which part of the world is the Great Barrier Reef located?", risposte: ["Mediterranean Sea", "Pacific Ocean (Australia)", "Caribbean Sea", "Indian Ocean"], corretta: 1 },
        { domanda: "What is 'dew'?", risposte: ["Light rain", "Atmospheric water vapor condensed on the ground at night", "Melted snow", "Groundwater"], corretta: 1 }
    ]
};